# Get the latest node docker container
image: node:latest

# Cache node_modules for future jobs
cache:
  paths:
    - frontend/node_modules/

variables:
  CI: 'true'

before_script:
  - cd frontend

stages:
  - Build
  - Linter
  - Tests

# Installs the packages needed for the React app
build:
  stage: Build
  script:
    - npm install
  artifacts:
    paths:
      - frontend/node_modules/

# Check style of the code
eslint:
  stage: Linter
  needs: [build]
  script:
    - npm run lint

# Run tests
test:
  stage: Tests
  needs: [eslint]
  script:
    - npm test -- --coverage --watchAll=false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/