# Get the latest node docker container
image: node:latest

# Cache node_modules for future jobs
cache:
  paths:
    - node_modules/

stages:
  - Build
  - Linter
  - Tests

# Installs the packages needed for the React app
build:
  stage: Build
  script:
    - npm install

# Check style of the code
eslint:
  stage: Linter
  script:
    - npx eslint src

# Run tests
test:
  stage: Tests
  script:
    - npm test -- --coverage --watchAll=false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/