"""Added role column to users table

Revision ID: 2fc5b6dfbfb5
Revises: b5565fa100b8
Create Date: 2020-09-15 12:34:30.402160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc5b6dfbfb5'
down_revision = 'b5565fa100b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('role', sa.String(length=20),
                            nullable=False,
                            server_default='view-only')
                  )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
